# Generated by Django 5.2.1 on 2025-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=100, unique=True, verbose_name='SKU ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('sales', models.IntegerField(default=0, verbose_name='Total Sales')),
                ('returns', models.IntegerField(default=0, verbose_name='Total Returns')),
                ('content_score', models.FloatField(default=0.0, verbose_name='Content Score')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'ordering': ['name'],
            },
        ),
    ]
