# Generated by Django 5.2.1 on 2025-06-04 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='returns',
        ),
        migrations.AddField(
            model_name='sku',
            name='return_percentage',
            field=models.FloatField(default=0, verbose_name='Returns Percentage'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Note Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='skus.sku', verbose_name='Associated SKU')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SKUDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Metric')),
                ('sales_units', models.IntegerField(default=0, verbose_name='Sales Units')),
                ('returns_units', models.IntegerField(default=0, verbose_name='Returned Units')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='skus.sku', verbose_name='Associated SKU')),
            ],
            options={
                'verbose_name': 'SKU Daily Metric',
                'verbose_name_plural': 'SKU Daily Metrics',
                'ordering': ['date'],
                'unique_together': {('sku', 'date')},
            },
        ),
    ]
